# Generated by Django 3.1 on 2020-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200809_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://data-flair.training/blogs/django-crud-example/'),
        ),
    ]
