# Generated by Django 3.1 on 2020-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
