# Generated by Django 3.1 on 2020-08-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('Project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='projects.project')),
            ],
        ),
    ]
