# Generated by Django 3.1 on 2020-08-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.details')),
            ],
        ),
    ]
