# Generated by Django 3.1 on 2020-08-10 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 4, 17, 3, 118931, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='moheed', max_length=80),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.TextField(default='good'),
        ),
    ]
