# Generated by Django 3.1 on 2020-08-10 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200810_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 4, 25, 13, 436167, tzinfo=utc)),
        ),
    ]
