# Generated by Django 2.2.15 on 2020-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200810_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='github',
            field=models.URLField(default='https://data-flair.training/blogs/django-crud-example/'),
        ),
    ]
