# Generated by Django 2.2.15 on 2020-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_details_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='moheed', max_length=80)),
                ('email', models.EmailField(default='a@gmail.com', max_length=254)),
                ('Review', models.TextField(default='good')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
